services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: kelvin
      POSTGRES_PASSWORD: localdevpassword
      POSTGRES_DB: kelvin_portfolio
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  