packages:
  - "."

allowBuilds:
  "@prisma/engines": true
  core-js: true
  esbuild: true
  prisma: true

onlyBuiltDependencies:
  - esbuild
  - lightningcss
  - "@prisma/engines"
  - prisma
  - core-js