import { defineArrayMember, defineField, defineType } from 'sanity'

const seo=[defineField({name:'metaTitle',type:'string'}),defineField({name:'metaDescription',type:'text'}),defineField({name:'ogImage',type:'image'})]
const block=defineField({name:'body',type:'array',of:[defineArrayMember({type:'block'}),defineArrayMember({type:'image',options:{hotspot:true}}),defineArrayMember({type:'code'})]})
export const schemaTypes=[
 defineType({name:'siteSettings',title:'Site settings',type:'document',fields:[defineField({name:'name',type:'string'}),defineField({name:'tagline',type:'string'}),defineField({name:'heroHeadline',type:'string'}),defineField({name:'heroSubcopy',type:'text'}),defineField({name:'statusBoard',type:'object',fields:[defineField({name:'label',type:'string'}),defineField({name:'statusText',type:'string'}),defineField({name:'stats',type:'array',of:[defineArrayMember({type:'object',fields:[defineField({name:'label',type:'string'}),defineField({name:'value',type:'string'}),defineField({name:'barLevel',type:'number',validation:r=>r.min(1).max(5)})]})]})]}),defineField({name:'contact',type:'object',fields:[defineField({name:'email',type:'string'}),defineField({name:'phone',type:'string'}),defineField({name:'linkedinUrl',type:'url'})]}),defineField({name:'location',type:'string'}),defineField({name:'availability',type:'string'}),defineField({name:'seo',type:'object',fields:seo})]}),
 defineType({name:'experience',type:'document',fields:[defineField({name:'title',type:'string',validation:r=>r.required()}),defineField({name:'organization',type:'string'}),defineField({name:'startDate',type:'date'}),defineField({name:'endDate',type:'date'}),defineField({name:'isCurrent',type:'boolean'}),defineField({name:'bullets',type:'array',of:[defineArrayMember({type:'string'})]}),defineField({name:'order',type:'number'})]}),


 defineType({name:'education',type:'document',fields:[defineField({name:'degree',type:'string'}),defineField({name:'institution',type:'string'}),defineField({name:'order',type:'number'})]}),
 defineType({name:'language',type:'document',fields:[defineField({name:'name',type:'string'}),defineField({name:'level',type:'string'}),defineField({name:'order',type:'number'})]}),

    
 defineType({name:'skillCategory',type:'document',fields:[defineField({name:'title',type:'string'}),defineField({name:'order',type:'number'}),defineField({name:'skills',type:'array',of:[defineArrayMember({type:'string'})]})]}),
 defineType({name:'capability',type:'document',fields:[defineField({name:'order',type:'number'}),defineField({name:'title',type:'string'}),defineField({name:'description',type:'text'})]}),
 defineType({name:'caseStudy',type:'document',fields:[defineField({name:'caseNumber',type:'number'}),defineField({name:'title',type:'string'}),defineField({name:'slug',type:'slug',options:{source:'title'}}),defineField({name:'year',type:'string'}),defineField({name:'organization',type:'string'}),defineField({name:'tags',type:'array',of:[defineArrayMember({type:'string'})]}),defineField({name:'summary',type:'text'}),...['approach','analysis','outcome'].map(name=>defineField({name,type:'array',of:[defineArrayMember({type:'block'})]})),defineField({name:'hasSampleDashboard',type:'boolean'}),defineField({name:'dashboardMock',type:'object',fields:[defineField({name:'quarterlyOutputData',type:'array',of:[defineArrayMember({type:'object',fields:[defineField({name:'label',type:'string'}),defineField({name:'value',type:'number'})]})]}),defineField({name:'coveragePercent',type:'number'}),defineField({name:'kpis',type:'array',of:[defineArrayMember({type:'object',fields:[defineField({name:'label',type:'string'}),defineField({name:'value',type:'string'}),defineField({name:'status',type:'string',options:{list:['on-track','below-target']}})]})]})]}),defineField({name:'order',type:'number'})]}),
 defineType({name:'post',type:'document',fields:[defineField({name:'title',type:'string'}),defineField({name:'slug',type:'slug',options:{source:'title'}}),defineField({name:'excerpt',type:'text'}),defineField({name:'coverImage',type:'image',options:{hotspot:true}}),block,defineField({name:'tags',type:'array',of:[defineArrayMember({type:'string'})]}),defineField({name:'publishedAt',type:'datetime'}),defineField({name:'seo',type:'object',fields:seo})]})
]
