/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as AdminDashboardRouteImport } from './routes/_admin.dashboard'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as ApiRevalidateRouteImport } from './routes/api.revalidate'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as AdminDashboardIndexRouteImport } from './routes/_admin.dashboard.index'
import { Route as AdminDashboardSectionRouteImport } from './routes/_admin.dashboard.$section'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminDashboardSectionIdRouteImport } from './routes/_admin.dashboard.$section.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/_admin/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRevalidateRoute = ApiRevalidateRouteImport.update({
  id: '/api/revalidate',
  path: '/api/revalidate',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardSectionRoute = AdminDashboardSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardSectionIdRoute = AdminDashboardSectionIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminDashboardSectionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/dashboard': typeof AdminDashboardRouteWithChildren
  '/api/contact': typeof ApiContactRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/$section': typeof AdminDashboardSectionRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof AdminDashboardIndexRoute
  '/dashboard/$section/$id': typeof AdminDashboardSectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard/$section': typeof AdminDashboardSectionRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof AdminDashboardIndexRoute
  '/dashboard/$section/$id': typeof AdminDashboardSectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/_admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/api/contact': typeof ApiContactRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/_admin/dashboard/$section': typeof AdminDashboardSectionRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_admin/dashboard/': typeof AdminDashboardIndexRoute
  '/_admin/dashboard/$section/$id': typeof AdminDashboardSectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/experience'
    | '/login'
    | '/portfolio'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/skills'
    | '/dashboard'
    | '/api/contact'
    | '/api/revalidate'
    | '/blog/$slug'
    | '/portfolio/$slug'
    | '/blog/'
    | '/dashboard/$section'
    | '/api/auth/$'
    | '/dashboard/'
    | '/dashboard/$section/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/experience'
    | '/login'
    | '/portfolio'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/skills'
    | '/api/contact'
    | '/api/revalidate'
    | '/blog/$slug'
    | '/portfolio/$slug'
    | '/blog'
    | '/dashboard/$section'
    | '/api/auth/$'
    | '/dashboard'
    | '/dashboard/$section/$id'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/experience'
    | '/login'
    | '/portfolio'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/skills'
    | '/_admin/dashboard'
    | '/api/contact'
    | '/api/revalidate'
    | '/blog/$slug'
    | '/portfolio/$slug'
    | '/blog/'
    | '/_admin/dashboard/$section'
    | '/api/auth/$'
    | '/_admin/dashboard/'
    | '/_admin/dashboard/$section/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ExperienceRoute: typeof ExperienceRoute
  LoginRoute: typeof LoginRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SkillsRoute: typeof SkillsRoute
  AdminDashboardRoute: typeof AdminDashboardRouteWithChildren
  ApiContactRoute: typeof ApiContactRoute
  ApiRevalidateRoute: typeof ApiRevalidateRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/revalidate': {
      id: '/api/revalidate'
      path: '/api/revalidate'
      fullPath: '/api/revalidate'
      preLoaderRoute: typeof ApiRevalidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/_admin/dashboard/': {
      id: '/_admin/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/_admin/dashboard/$section': {
      id: '/_admin/dashboard/$section'
      path: '/$section'
      fullPath: '/dashboard/$section'
      preLoaderRoute: typeof AdminDashboardSectionRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard/$section/$id': {
      id: '/_admin/dashboard/$section/$id'
      path: '/$id'
      fullPath: '/dashboard/$section/$id'
      preLoaderRoute: typeof AdminDashboardSectionIdRouteImport
      parentRoute: typeof AdminDashboardSectionRoute
    }
  }
}

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

interface AdminDashboardSectionRouteChildren {
  AdminDashboardSectionIdRoute: typeof AdminDashboardSectionIdRoute
}

const AdminDashboardSectionRouteChildren: AdminDashboardSectionRouteChildren = {
  AdminDashboardSectionIdRoute: AdminDashboardSectionIdRoute,
}

const AdminDashboardSectionRouteWithChildren =
  AdminDashboardSectionRoute._addFileChildren(
    AdminDashboardSectionRouteChildren,
  )

interface AdminDashboardRouteChildren {
  AdminDashboardSectionRoute: typeof AdminDashboardSectionRouteWithChildren
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

const AdminDashboardRouteChildren: AdminDashboardRouteChildren = {
  AdminDashboardSectionRoute: AdminDashboardSectionRouteWithChildren,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}

const AdminDashboardRouteWithChildren = AdminDashboardRoute._addFileChildren(
  AdminDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ExperienceRoute: ExperienceRoute,
  LoginRoute: LoginRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SkillsRoute: SkillsRoute,
  AdminDashboardRoute: AdminDashboardRouteWithChildren,
  ApiContactRoute: ApiContactRoute,
  ApiRevalidateRoute: ApiRevalidateRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
